services:
  dspace:
    environment:
      dspace__P__name: UIST Digital Repository
      mail__P__server: mailpit
      mail__P__server__P__port: 1025
      mail__P__from__P__address: test@grr.la
      mail__P__admin: test@grr.la
      feedback__P__recipient: test@grr.la
    depends_on:
      - mailpit
  dspacedb:
    ports: !override
      - published: 5433
        target: 5432
  mailpit:
    image: axllent/mailpit:latest
    container_name: dspace-mailpit
    networks:
      - dspacenet
    ports:
      - published: 1025
        target: 1025
      - published: 8025
        target: 8025
