# Mapping between DSpace common publication's types and a schema.org URI
Animation = https://schema.org/3DModel
Article = https://schema.org/ScholarlyArticle
Book = https://schema.org/Book
Book\ chapter = https://schema.org/Chapter
Chapter = https://schema.org/Chapter
Conference\ abstract = https://schema.org/ScholarlyArticle
Conference\ paper = https://schema.org/ScholarlyArticle
Dataset = https://schema.org/Dataset
Dissertation = https://schema.org/Thesis
Learning\ Object = https://schema.org/LearningResource
Image = https://schema.org/ImageObject
Image,\ 3-D = https://schema.org/3DModel
Map = https://schema.org/Map
Musical\ Score = https://schema.org/MusicComposition
Plan\ or\ blueprint = https://schema.org/Map
Preprint = https://schema.org/ScholarlyArticle
Presentation = https://schema.org/PresentationDigitalDocument
Recording,\ acoustical = https://schema.org/MusicRecording
Recording,\ musical = https://schema.org/MusicRecording
Recording,\ oral = https://schema.org/MusicRecording
Software = https://schema.org/SoftwareSourceCode
SoftwareSourceCode = https://schema.org/SoftwareSourceCode
Source\ Code = https://schema.org/SoftwareSourceCode
Technical\ Report = https://schema.org/Report
Thesis = https://schema.org/Thesis
Academic\ work = https://schema.org/Thesis
Report = https://schema.org/Report
Video = https://schema.org/VideoObject
Working\ Paper = https://schema.org/Report
Other = https://schema.org/CreativeWork
